### ISSUE TITLE
Installation instructions - error with node 16.13.1, worked fine with node 14.18.2

### ISSUE THREAD

**Issue by mmmg00d** [iron-fish/ironfish#792]
Installing Iron Fish from source (on Ubuntu 18.x), and the current installation instructions specify Node.js 16.x, so I installed 16.13.1. When running `yarn install`, I got the following error, which is expecting node 14.x. 

`[1/4] Resolving packages...
[2/4] Fetching packages...
error ironfish-cli@0.0.0: The engine "node" is incompatible with this module. Expected version "14.x". Got "16.13.1"
error Found incompatible module.
`

So, I installed Node.js 14.18.2 and switched to v14.18.2 and then re-ran `yarn install` and the install worked fine.

I followed the installation instructions here: https://github.com/iron-fish/ironfish#initial-setup

**Comment by dguenther** [comment]
The current version of master requires Node 16, so you may be running an older version of the code. See here: https://github.com/iron-fish/ironfish/blob/master/ironfish-cli/package.json

Make sure your branch is set to `master` and `git pull` to fetch the latest commits, then if it still doesn't work with Node 16, please add a comment with the first few lines from `git log` in your `ironfish` folder.

**Comment by mmmg00d** [comment]
Thank you. I ran `git pull` on `master` and updated the code. 

A new issue...when I run `yarn start` from the ironfish-cli directory, I see the following errors. 

```
../ironfish/src/primitives/note.ts(5,36): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/primitives/noteEncrypted.ts(5,54): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/merkletree/hasher.ts(4,54): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/primitives/nullifier.ts(5,30): error TS2307: Cannot find module '@napi-rs/blake-hash' or its corresponding type declarations.
../ironfish/src/workerPool/tasks/createMinersFee.ts(5,61): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/workerPool/tasks/createTransaction.ts(5,35): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/workerPool/worker.ts(6,29): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/workerPool/tasks/transactionFee.ts(5,35): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/workerPool/tasks/verifyTransaction.ts(4,35): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/memPool/memPool.ts(6,31): error TS2307: Cannot find module 'fastpriorityqueue' or its corresponding type declarations.
../ironfish/src/memPool/memPool.ts(30,55): error TS7006: Parameter 'firstTransaction' implicitly has an 'any' type.
../ironfish/src/memPool/memPool.ts(30,73): error TS7006: Parameter 'secondTransaction' implicitly has an 'any' type.
../ironfish/src/memPool/memPool.ts(153,27): error TS7006: Parameter 't' implicitly has an 'any' type.
../ironfish/src/primitives/transaction.ts(5,35): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/genesis/makeGenesisBlock.ts(10,8): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/account/accounts.ts(5,55): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
../ironfish/src/primitives/blockheader.ts(13,24): error TS2307: Cannot find module '@napi-rs/blake-hash' or its corresponding type declarations.
../ironfish/src/testUtilities/fixtures.ts(5,29): error TS2307: Cannot find module 'ironfish-rust-nodejs' or its corresponding type declarations.
```
Any suggestions for a fix? Or just reinstall?

**Comment by mmmg00d** [comment]
All set - just had to run `yarn install` again in my root directory. Thanks @dguenther

**Comment by dguenther** [comment]
Great, glad it's working for you!
