### ISSUE TITLE
Disconnected due to TypeError: this._items.at is not a function

### ISSUE THREAD

**Issue by gjfrn** [iron-fish/ironfish#2376]
### What happened?

Since updating from 0.1.47, peers keep getting disconnected due to the error in the log. This prevents my node from syncing.

### Version

0.1.49

### Debug output

```shell
Stopping sync from EUFyGNb (MSI2020) due to /Users/test/ironfish/ironfish/src/memPool/priorityQueue.ts:67
    return this._items.at(0)
                       ^

TypeError: this._items.at is not a function
    at PriorityQueue.peek (/Users/test/ironfish/ironfish/src/memPool/priorityQueue.ts:67:24)
    at MemPool.onConnectBlock (/Users/test/ironfish/ironfish/src/memPool/memPool.ts:169:44)
    at null.<anonymous> (/Users/test/ironfish/ironfish/src/memPool/memPool.ts:66:12)
    at Event.emitAsync (/Users/test/ironfish/ironfish/src/event.ts:65:31)
    at Blockchain.addHeadToChain (/Users/test/ironfish/ironfish/src/blockchain/blockchain.ts:726:31)
    at Blockchain.connect (/Users/test/ironfish/ironfish/src/blockchain/blockchain.ts:584:7)
    at null.<anonymous> (/Users/test/ironfish/ironfish/src/blockchain/blockchain.ts:371:31)
    at LevelupDatabase.withTransaction (/Users/test/ironfish/ironfish/src/storage/database/database.ts:211:22)
    at Blockchain.addBlock (/Users/test/ironfish/ironfish/src/blockchain/blockchain.ts:341:23)
    at Syncer.addBlock (/Users/test/ironfish/ironfish/src/syncer.ts:423:40)
Peer EUFyGNb (MSI2020) disconnected (DISCONNECTED) while syncing.
```

### Relevant log output

```shell
Stopping sync from EUFyGNb (MSI2020) due to /Users/test/ironfish/ironfish/src/memPool/priorityQueue.ts:67
    return this._items.at(0)
                       ^

TypeError: this._items.at is not a function
    at PriorityQueue.peek (/Users/test/ironfish/ironfish/src/memPool/priorityQueue.ts:67:24)
    at MemPool.onConnectBlock (/Users/test/ironfish/ironfish/src/memPool/memPool.ts:169:44)
    at null.<anonymous> (/Users/test/ironfish/ironfish/src/memPool/memPool.ts:66:12)
    at Event.emitAsync (/Users/test/ironfish/ironfish/src/event.ts:65:31)
    at Blockchain.addHeadToChain (/Users/test/ironfish/ironfish/src/blockchain/blockchain.ts:726:31)
    at Blockchain.connect (/Users/test/ironfish/ironfish/src/blockchain/blockchain.ts:584:7)
    at null.<anonymous> (/Users/test/ironfish/ironfish/src/blockchain/blockchain.ts:371:31)
    at LevelupDatabase.withTransaction (/Users/test/ironfish/ironfish/src/storage/database/database.ts:211:22)
    at Blockchain.addBlock (/Users/test/ironfish/ironfish/src/blockchain/blockchain.ts:341:23)
    at Syncer.addBlock (/Users/test/ironfish/ironfish/src/syncer.ts:423:40)
Peer EUFyGNb (MSI2020) disconnected (DISCONNECTED) while syncing.
```

### Graffiti

GFIRONFISH

**Comment by gjfrn** [comment]
Still getting this issue with 1.51

**Comment by JonasDe** [comment]
Can confirm, I am affected as well.

Upgraded from 1.47 to 1.51 and this is a permanent issue right now

**Comment by JonasDe** [comment]
I was able to work around this by changing priorityQueue line 67 from _items.at(0) to items[0]
 
 This is a temporary mitigation.
 
 The other way I was able to work around was by using node version 18.7 (which is above the recommended version in the docs). But seems to work for me so that's how I'm moving forward now

**Comment by SSHsdy001** [comment]
I have also encountered this problem, and the [0] method does not work. Do you have solution？thank you.

**Comment by JonasDe** [comment]
Sorry you have to change it to `_items[0]`

I forgot the underscore in my comment, but it's what I did

**Comment by SSHsdy001** [comment]
Thanks for help.I have already try, it dosn't work.---- Replied Message ----FromJonas ***@***.***>Date11/09/2022 16:44 ***@***.***> ***@***.******@***.***>SubjectRe: [iron-fish/ironfish] Disconnected due to TypeError: this._items.at is not a function (Issue #2376)
Sorry you have to change it to _items[0]
I forgot the underscore in my comment, but it's what I did

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iron-fish/ironfish/issues/2376#issuecomment-1308409521",
"url": "https://github.com/iron-fish/ironfish/issues/2376#issuecomment-1308409521",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by danield9tqh** [comment]
Thank you for reporting @gjfrn, @JonasDe and @SSHsdy001. I've added a fix [here](https://github.com/iron-fish/ironfish/pull/2708) and apologies for the late fix. Just to confirm the issue do you know which NodeJS versions you were running on? It seems like the `.at` method is only supported [after version 16.6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility). You can check by running `node --version` on your machine. This is most likely the issue but just want to confirm. Thanks!

**Comment by NullSoldier** [comment]
We're also going to enforce node version 16 to narrow down these issues. Please open the ticket again after the next release in 0.1.54.
