### ISSUE TITLE
TypeError: blocks.at is not a function

### ISSUE THREAD

**Issue by SSHsdy001** [iron-fish/ironfish#2605]
### What happened?

What happened?
Since updating from 0.1.52, peers keep getting disconnected due to the error in the log. This prevents my node from syncing.

Version
0.1.52

### Version

0.1.52 @

### Debug output

```shell
Stopping sync from tRHdVje (tetsugyo) due to TypeError: blocks.at is not a function
    at Syncer.syncBlocks (/root/ironfish/ironfish/build/src/syncer.js:264:38)
    at async Syncer.syncFrom (/root/ironfish/ironfish/build/src/syncer.js:144:9)
Peer tRHdVje (tetsugyo) disconnected (DISCONNECTED) while syncing.
Starting sync from B5uAUqk (tetsugyo). work: +208897302086269167, ours: 274597, theirs: 274837
Finding ancestor using linear search on last 3 blocks starting at 00000...b905b (274597) from peer B5uAUqk (tetsugyo) at 274837
Found peer B5uAUqk (tetsugyo) ancestor 00000...ff83c, syncing from 274595 -> 274837 (242) after 2 requests
Requesting 5 blocks starting at 00000...ff83c (274595) from B5uAUqk (tetsugyo)
Stopping sync from B5uAUqk (tetsugyo) due to TypeError: blocks.at is not a function
    at Syncer.syncBlocks (/root/ironfish/ironfish/build/src/syncer.js:264:38)
    at async Syncer.syncFrom (/root/ironfish/ironfish/build/src/syncer.js:144:9)
Peer B5uAUqk (tetsugyo) disconnected (DISCONNECTED) while syncing.
Starting sync from m6wiRnc. work: +209769847024059105, ours: 274597, theirs: 274838
Finding ancestor using linear search on last 3 blocks starting at 00000...b905b (274597) from peer m6wiRnc at 274838
Found peer m6wiRnc ancestor 00000...ff83c, syncing from 274595 -> 274838 (243) after 2 requests
Requesting 5 blocks starting at 00000...ff83c (274595) from m6wiRnc
Stopping sync from m6wiRnc due to TypeError: blocks.at is not a function
    at Syncer.syncBlocks (/root/ironfish/ironfish/build/src/syncer.js:264:38)
    at async Syncer.syncFrom (/root/ironfish/ironfish/build/src/syncer.js:144:9)
Peer m6wiRnc disconnected (DISCONNECTED) while syncing.
```

### Relevant log output

```shell
Stopping sync from tRHdVje (tetsugyo) due to TypeError: blocks.at is not a function
    at Syncer.syncBlocks (/root/ironfish/ironfish/build/src/syncer.js:264:38)
    at async Syncer.syncFrom (/root/ironfish/ironfish/build/src/syncer.js:144:9)
Peer tRHdVje (tetsugyo) disconnected (DISCONNECTED) while syncing.
Starting sync from B5uAUqk (tetsugyo). work: +208897302086269167, ours: 274597, theirs: 274837
Finding ancestor using linear search on last 3 blocks starting at 00000...b905b (274597) from peer B5uAUqk (tetsugyo) at 274837
Found peer B5uAUqk (tetsugyo) ancestor 00000...ff83c, syncing from 274595 -> 274837 (242) after 2 requests
Requesting 5 blocks starting at 00000...ff83c (274595) from B5uAUqk (tetsugyo)
Stopping sync from B5uAUqk (tetsugyo) due to TypeError: blocks.at is not a function
    at Syncer.syncBlocks (/root/ironfish/ironfish/build/src/syncer.js:264:38)
    at async Syncer.syncFrom (/root/ironfish/ironfish/build/src/syncer.js:144:9)
Peer B5uAUqk (tetsugyo) disconnected (DISCONNECTED) while syncing.
Starting sync from m6wiRnc. work: +209769847024059105, ours: 274597, theirs: 274838
Finding ancestor using linear search on last 3 blocks starting at 00000...b905b (274597) from peer m6wiRnc at 274838
Found peer m6wiRnc ancestor 00000...ff83c, syncing from 274595 -> 274838 (243) after 2 requests
Requesting 5 blocks starting at 00000...ff83c (274595) from m6wiRnc
Stopping sync from m6wiRnc due to TypeError: blocks.at is not a function
    at Syncer.syncBlocks (/root/ironfish/ironfish/build/src/syncer.js:264:38)
    at async Syncer.syncFrom (/root/ironfish/ironfish/build/src/syncer.js:144:9)
Peer m6wiRnc disconnected (DISCONNECTED) while syncing.
```

### Graffiti

sshsdy001

**Comment by NullSoldier** [comment]
This is a duplicate of this issue, https://github.com/iron-fish/ironfish/issues/2376
